import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const PORT = 3000;

// Lazy initialization of Gemini client to prevent crashes if key is missing on startup
let aiClient: GoogleGenAI | null = null;
function getAi(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured in environment secrets.");
  }
  if (!aiClient) {
    aiClient = new GoogleGenAI({ apiKey });
  }
  return aiClient;
}

async function startServer() {
  const app = express();
  app.use(express.json());

  // Health check endpoint
  app.get("/api/health", (_req, res) => {
    res.json({ status: "ok", service: "mystic-realm-audio" });
  });

  // Music generation endpoint using Lyria 3 (lyria-3-clip-preview)
  app.post("/api/generate-music", async (req, res) => {
    try {
      const { prompt, duration = 30 } = req.body || {};
      const musicPrompt =
        prompt ||
        "A sparkling gaming mystery soundtrack with shimmering crystal bells, curious staccato marimba, enchanted arpeggios, and an intriguing puzzle-solving fantasy atmosphere.";

      const ai = getAi();

      // Lyria 3 clip preview generates up to 30-second music clips
      const response = await ai.models.generateContentStream({
        model: "lyria-3-clip-preview",
        contents: `${musicPrompt} Duration: ${duration}s. Intriguing, mystical, sparkling gaming style.`,
      });

      let audioBase64 = "";
      let lyrics = "";
      let mimeType = "audio/wav";

      for await (const chunk of response) {
        const parts = chunk.candidates?.[0]?.content?.parts;
        if (!parts) continue;

        for (const part of parts) {
          if (part.inlineData?.data) {
            if (!audioBase64 && part.inlineData.mimeType) {
              mimeType = part.inlineData.mimeType;
            }
            audioBase64 += part.inlineData.data;
          }
          if (part.text && !lyrics) {
            lyrics = part.text;
          }
        }
      }

      if (!audioBase64) {
        throw new Error("No audio content was generated by the Lyria model.");
      }

      res.json({
        success: true,
        audioBase64,
        mimeType,
        lyrics,
        prompt: musicPrompt,
      });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Failed to generate music track";
      console.error("Lyria music generation error:", message);
      res.status(500).json({
        success: false,
        error: message,
      });
    }
  });

  // Vite middleware setup
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Failed to start server:", err);
  process.exit(1);
});
